- .editorconfig
- build.gradle.kts
- src/main/kotlin/com/deepromeet/atcha/common/dto/Cursor.kt
- src/main/kotlin/com/deepromeet/atcha/common/feign/CustomErrorDecoder.kt
- src/main/kotlin/com/deepromeet/atcha/common/feign/FeignConfig.kt
- src/main/kotlin/com/deepromeet/atcha/common/feign/FeignCustomError.kt
- src/main/kotlin/com/deepromeet/atcha/common/web/ApiResponse.kt
- src/main/kotlin/com/deepromeet/atcha/common/web/GlobalControllerAdvice.kt
- src/main/kotlin/com/deepromeet/atcha/common/web/SliceResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/controller/LocationController.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/request/LocationSearchRequest.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/response/LocationResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/response/LocationSearchResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/Coordinate.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/Location.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationReader.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationService.kt
- src/main/kotlin/com/deepromeet/atcha/location/exception/LocationError.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationClient.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/request/TMapPOIRequest.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/response/TMapPOIResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/TMapTransitClient.kt
- #1
- Spring Cloud Open Feign 초기 설정
- TMap API 경로 조회 예시 코드
- 프로젝트 이름 변경
- 계층별 예외 삭제
- intellij profile을 `local`로 설정해주세요!
> [#1] feign 초기 설정 및 예시 코드

- Makefile
- docker/common.yml
- docker/mysql/mysql.yml
- docker/redis/redis.yml
- close #17 
-
`make up` 명령어를 사용하면 mysql과 redis가 올라갑니다 `make down` 을 하시면 내려가용
추가로 혹시 로컬에 이미 설치되어있는 mysql이나 redis와 충돌날수도있어서 포트포워딩을 다르게 설정해두었습니다!
> [#17] 로컬환경 docker compose 설정

- src/main/kotlin/com/deepromeet/atcha/location/api/controller/LocationController.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationReader.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationService.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/POIFinder.kt
- src/main/kotlin/com/deepromeet/atcha/location/exception/LocationError.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationClient.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationFeignClient.kt
- close #7 
- ~~tmap poi api를 통해 장소 통합 검색 구현~~
- ~~spring.data의 Slice 객체를 변환하여 반환 -> 클라이언트 무한 스크롤 구현~~
- ~~spring.data의 Slice에는 필요없는 정보가 너무 많아 커스텀 SliceResponse로 반환~~
Slice로 구현했다가 전에 디자인에 문의결과 20개로 제한하자고해서 LIst로 변경했습니다!
> [#7] 장소 통합 검색 API 구현

- .github/workflows/dev-deploy.yml
- docker/redis/redis.yml
- src/main/kotlin/com/deepromeet/atcha/auth/api/controller/AuthController.kt
- src/main/kotlin/com/deepromeet/atcha/auth/api/request/SignUpRequest.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/AuthProviders.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/AuthService.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/Provider.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/UserToken.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/UserTokenAppender.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/response/KakaoUserInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/response/ProviderUserInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/TokenArgumentResolver.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/controller/LocationController.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/response/LocationResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationReader.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationService.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/POIFinder.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/ReverseLabeler.kt
- src/main/kotlin/com/deepromeet/atcha/location/exception/LocationError.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationClient.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationFeignClient.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/Address.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/User.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserAppender.kt
- src/test/kotlin/com/deepromeet/atcha/auth/AuthControllerTest.kt
- src/test/kotlin/com/deepromeet/atcha/auth/AuthServiceTest.kt
- src/test/kotlin/com/deepromeet/atcha/user/UserControllerTest.kt
- close #23 
- CI CD 실패시 빠르게 다시 돌려볼 수 있도록 수동 트리거인 workflow_dispatch 설정을 추가했습니다. ([참고](https://www.hahwul.com/2020/10/18/how-to-trigger-github-action-manually/))
-
> [#23] workflow_dispatch 추가

- deployment/dev/docker-compose.yml
- src/main/kotlin/com/deepromeet/atcha/auth/api/controller/AuthController.kt
- close #31 
- 환경 변수를 도커에서 직접 넣어주고 있었던 것이 에러를 발생시키고 있었습니다! 이 부분을 삭제했어요!
> [#31] CD 환경 변수 삭제

- src/main/kotlin/com/deepromeet/atcha/auth/api/request/SignUpRequest.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/SignUpInfo.kt
- src/main/kotlin/com/deepromeet/atcha/user/api/request/UserInfoUpdateRequest.kt
- src/test/kotlin/com/deepromeet/atcha/auth/AuthControllerTest.kt
- src/test/kotlin/com/deepromeet/atcha/support/fixture/UserFixture.kt
- src/test/kotlin/com/deepromeet/atcha/user/UserControllerTest.kt
- close #39 
- 테스트의 편의성을 위해 테스트용 User를 생성하는 UserFixture를 만들었습니다.
- UserFixture.create()로 기본 설정된 테스트 유저를 생성하여 사용하시면 됩니다!
- 변경사항이 있을때만 create에 파라미터로 전달하시면 돼요! ex) `val user = UserFixture.create(nickname = "새로운 이름")`
- 유저 객체만 생성하고 DB에는 저장되어 있지 않기 때문에 필요에 따라 userAppender를 활용해 DB에 save해주시면 됩니다!
> [#39] 테스트 Fixture 도입

- .github/workflows/dev-deploy.yml
- close #50 
CD가 문법 오류로 돌아가지 않아요 ㅠㅠ
> [#50] CD 문법 오류 수정

- .github/workflows/prod-deploy.yml
- close #54 
Prod CD 파이프라인 구축
-
> [#54]  운영 환경 파이프라인 설정

- src/main/kotlin/com/deepromeet/atcha/auth/domain/AuthService.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/UserProviderAppender.kt
- src/main/kotlin/com/deepromeet/atcha/common/feign/CustomErrorDecoder.kt
- src/main/kotlin/com/deepromeet/atcha/common/feign/FeignConfig.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationReader.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserReader.kt
- src/main/kotlin/com/deepromeet/atcha/user/infrastructure/repository/UserJpaRepository.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/kotlin/com/deepromeet/atcha/auth/AuthControllerTest.kt
- src/test/kotlin/com/deepromeet/atcha/user/UserControllerTest.kt
- close #52 
개발 환경이 제대로 띄어지지 않은 문제를 해결합니다.
-
> [#52] 서브 모듈 최신화

- .editorconfig
- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- .github/workflows/prod-integration.yml
- deployment/dev/deploy.sh
- deployment/dev/docker-compose.yml
- src/main/resources/application-prod.yml
- src/test/kotlin/com/deepromeet/atcha/auth/AuthServiceTest.kt
- src/test/kotlin/com/deepromeet/atcha/support/fixture/ProviderFixture.kt
- src/test/resources/application.yml
- close #56 
- 서버 2개 배포
- DB 1개 배포
- Redis 1개 배포
- Prod CD 파이프라인 구축
> [#56] 운영 환경 배포

- .github/workflows/prod-integration.yml
- src/main/kotlin/com/deepromeet/atcha/common/token/TokenBlacklist.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/TokenGenerator.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/TokenType.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/infrastructure/cache/TokenRedisBlacklist.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/infrastructure/cache/TokenRedisConfig.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/kotlin/com/deepromeet/atcha/auth/AuthControllerTest.kt
- src/test/kotlin/com/deepromeet/atcha/auth/TokenGeneratorTest.kt
- close #48 
- 분산 서버 환경에서 블랙 리스트가 동작할 수 있도록 redis 적용
> [#48] 블랙리스트 redis 적용

- src/main/resources/application-prod.yml
- src/main/resources/application-test.yml
- src/test/resources/application.yml
> [#63] 환경 변수 누락 해결

- .githooks/pre-push
- close #70 
- 서브 모듈 변경 사항만 감지하도록 변경
> [#70] pre-push 수정

- .githooks/pre-commit
- src/main/kotlin/com/deepromeet/atcha/transit/domain/SubwayManager.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicGyeonggiResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/repository/SubwayStationRepository.kt
- close #72
- 지하철 이름 조회 LIKE 추가
- 버스 API 응답 non-null 필드 수정
- pre-commit ktlintFormat으로 변경
```kotlin
@Query(
"""
SELECT s
FROM SubwayStation s
WHERE s.routeCode = :routeCode
AND ( s.name = :name OR s.name LIKE CONCAT(:name, '(%') )
"""
)
fun findByRouteCodeAndNameOrLike(
routeCode: String,
name: String
): SubwayStation?
```
-
> [#72] 지하철 조회 및 버스 API 응답 오류 해결

- build.gradle.kts
- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/request/LastRoutesRequest.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
> feat: 막차 조회 coroutines 적용

- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationScheduler.kt
> refactor: ktlintFormat

- build.gradle.kts
- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusArrivalInfoFetcher.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusManager.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/SubwayInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/SubwayLine.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/SubwayManager.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicGyeonggiArrivalInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicGyeonggiStationInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicHolidayClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicSeoulBusArrivalInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicSeoulBusStationInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicSubwayInfoClient.kt
> [#84] nullable 반환 변경 및 로깅 추가

- .githooks/pre-commit
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/RouteNotificationRedisOperations.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/response/LastRoutesResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/response/RealTimeBusArrivalResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusArrival.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusRoute.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusRouteId.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteAppender.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteCache.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteReader.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/RouteDepartureTimeRefresher.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/exception/TransitError.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/cache/LastRouteRedisCache.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicBusResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicGyeonggiResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicJsonResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/scheduler/LastRouteScheduler.kt
- close #90 
- close #91 
- close #93
-
-
> [#90] 출발 남은 시간 / 버스 도착 정보 / 경로 상세 조회

- src/main/kotlin/com/deepromeet/atcha/auth/api/controller/AuthController.kt
- src/main/kotlin/com/deepromeet/atcha/auth/api/request/SignUpRequest.kt
- src/main/kotlin/com/deepromeet/atcha/auth/api/response/LoginResponse.kt
- src/main/kotlin/com/deepromeet/atcha/auth/api/response/SignUpResponse.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/AuthService.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/SignUpInfo.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/UserAuthInfo.kt
- src/main/kotlin/com/deepromeet/atcha/user/api/request/UserInfoUpdateRequest.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/User.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserAppender.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserUpdateInfo.kt
- src/test/kotlin/com/deepromeet/atcha/auth/AuthControllerTest.kt
- src/test/kotlin/com/deepromeet/atcha/auth/AuthServiceTest.kt
- src/test/kotlin/com/deepromeet/atcha/support/fixture/UserFixture.kt
- close #75 
- 로그인 및 회원가입시 FCM 토큰을 받도록 변경했습니다.
- 응답으로 사용자의 주소지 위경도가 포함되도록 변경되었습니다.
> [#75] 사용자 인증 과정 FCM 토큰 포함 및 응답에 주소시 위경도 포함

- src/main/kotlin/com/deepromeet/atcha/common/redis/RedisConfig.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteIndexAppender.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteIndexCache.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteIndexReader.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperations.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/cache/LastRouteIndexRedisCache.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/cache/LastRouteRedisCache.kt
- close #89 
- 출발지/도착지 캐시 (이미 존재하는 출발지/도착지 조회 시 캐시된 데이터 내려줌)
- SUBWAY 급행인 경우 제거하도록 필터 추가
- 내부 반복문 코루틴 추가
-
> [#89] 막차 조회 개선

- .github/workflows/staging-deploy.yml
- deployment/staging/data/nginx/nginx-blue.conf
- deployment/staging/data/nginx/nginx-green.conf
- deployment/staging/data/nginx/nginx.conf
- deployment/staging/deploy.sh
- deployment/staging/docker-compose.yml
- src/main/resources/application-staging.yml
- close #83 
- Staging 환경 구축
- 모니터링은 Prod 작업 리팩터링 이후 진행하겠습니다! Public IP를 더이상 발급 못해서 진행이 어려워요ㅠㅠ
> [#83] 스테이징 환경 구축(서브모듈 깃 꼬임 해결)

- src/main/kotlin/com/deepromeet/atcha/location/api/response/POIResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/DailyType.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicGyeonggiResponse.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> [#102] 환경 변수 추가 및 버스 운행 시간 공휴일 추가

- src/main/kotlin/com/deepromeet/atcha/location/api/response/POIResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationReader.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/POI.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/response/TMapPOIResponse.kt
> [#109] 미터 단위 표시 오류 및 키워드 공백 시 빈리스트 반환

- src/main/kotlin/com/deepromeet/atcha/common/logging/LoggingInterceptor.kt
> [#111] 헬스 체크 로깅 제거

- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-staging.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/kotlin/com/deepromeet/atcha/support/fixture/UserFixture.kt
- src/test/resources/application.yml
- close #107 
- 공동적으로 사용하는 환경 변수는 application.yaml에 정의하는 방식으로 통일했습니다.
> [#107] 동일 환경 변수 분리 처리

- .github/workflows/staging-deploy.yml
> [#115] Staging 설정 수정

- .github/workflows/staging-deploy.yml
- close #117 
Staging CD 트리거를 수정합니다.
> [#117] Staging CD trigger 수정

- src/main/kotlin/com/deepromeet/atcha/location/api/request/POIHistoryRequest.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/response/LocationResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/api/response/POIResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/Location.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationReader.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/POI.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/ReverseGeocoder.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/ReverseLabeler.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationClient.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/TMapLocationFeignClient.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/response/TMapPOIResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/response/TMapReverseGeocodingResponse.kt
- src/main/kotlin/com/deepromeet/atcha/location/infrastructure/client/response/TMapReverseLabelResponse.kt
- close #
- 기존 상호명만 반환했는데 도로명 주소도 함께 반환하도록 변경
-
> [#124] 리버스 지오코딩 도로명/상호명 반환

- src/main/kotlin/com/deepromeet/atcha/location/api/controller/LocationController.kt
- src/main/kotlin/com/deepromeet/atcha/location/domain/LocationService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/response/LastRoutesResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusArrival.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteReader.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicSeoulBusPositionFeignClient.kt
- src/main/resources/application-test.yml
- src/main/resources/application.yml
> [#129] 테스트 실패 해결

- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
> fix: 엔드포인트 오타 수정

- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationManager.kt
> [#133] 알림 data 전송 시 route 정보 제거

- src/main/kotlin/com/deepromeet/atcha/auth/exception/AuthError.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/exception/TokenError.kt
- src/main/kotlin/com/deepromeet/atcha/user/exception/UserError.kt
- close #138 
- 에러코드를 컨벤션에 맞게 변경하였습니다.
> [#138] 에러코드 컨벤션 통일

- src/main/kotlin/com/deepromeet/atcha/transit/api/response/LastRoutesResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
> [#142] LastRouteLeg NPE 해결

- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusArrival.kt
- src/main/resources/application-dev.yml
> fix: application.yml url 제거

- src/main/kotlin/com/deepromeet/atcha/transit/api/response/LastRoutesResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperations.kt
- close #
- 막차 경로 totalWorkDistance 누락 해결
-
> fix: totalWorkDistance 추가

- src/main/kotlin/com/deepromeet/atcha/common/token/TokenBlacklist.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/TokenGenerator.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/TokenType.kt
- src/main/kotlin/com/deepromeet/atcha/common/token/infrastructure/cache/TokenRedisBlacklist.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-staging.yml
- src/main/resources/application-test.yml
- src/test/kotlin/com/deepromeet/atcha/auth/TokenGeneratorTest.kt
- close #151 
- 환경마다 다른 토큰 만료 기간을 환경변수로 관리합니다.
> [#151] 토큰 만료 기간 환경변수로 분리

- src/main/kotlin/com/deepromeet/atcha/common/logging/interceptor/DefaultLoggingInterceptor.kt
- close #153 
- 테스트 프로필에서 DefaultLogger 빈을 조회하도록 Profile을 추가했습니다.
> [#153] 테스트 환경에서 빈 조회 실패 해결

- .github/workflows/dev-integration.yml
- close #155 
- 개발 환경에 올리기 전에 테스트를 돌리도록 CI를 추가합니다.
> [#155] Dev CI 추가

- src/main/kotlin/com/deepromeet/atcha/notification/api/NotificationController.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationManager.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationService.kt
- close #160 
- 푸시 알림 테스트 API를 추가합니다.
> [#160] 푸시 알림 테스트 API

- src/main/kotlin/com/deepromeet/atcha/transit/api/request/BusArrivalRequest.kt
> fix: 파라미터 수정

- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
- src/main/kotlin/com/deepromeet/atcha/transit/api/request/BusArrivalRequest.kt
> [#164] 버스 구분 파싱

- src/main/kotlin/com/deepromeet/atcha/notification/api/NotificationController.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationManager.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationService.kt
> [#135] 막차 알림 등록 제안 API 구현

- src/main/kotlin/com/deepromeet/atcha/common/redis/RedisConfig.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationManager.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/RouteNotificationRedisOperations.kt
- src/main/kotlin/com/deepromeet/atcha/notification/infrastructure/scheduler/NotificationScheduler.kt
- src/test/kotlin/com/deepromeet/atcha/scheduler/NotificationManagerTest.kt
- src/test/kotlin/com/deepromeet/atcha/support/BaseServiceTest.kt
- src/test/kotlin/com/deepromeet/atcha/support/fixture/UserNotificationFixture.kt
- close #169 
- Redis 분산락을 활용해서 푸시 알림 중복 전송을 해결했습니다.
관련 문서는 정리해서 노션에 업데이트 해두겠습니다!
> [#169] 푸시 알림 중복 처리

- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationManager.kt
- close #175 
- 개행을 삭제하여 ktlint 성공 처리
> [#175] ktlint 실패하는 개행 제거

- src/main/kotlin/com/deepromeet/atcha/common/redis/DefaultRedisConfig.kt
- src/main/kotlin/com/deepromeet/atcha/common/redis/ProdRedisConfig.kt
- src/main/kotlin/com/deepromeet/atcha/common/redis/RedisConfig.kt
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-staging.yml
- src/main/resources/application-test.yml
- close #184 
- Redis에 비밀번호 설정을 추가합니다.
> [#184] Redis 비밀번호 적용

- src/main/kotlin/com/deepromeet/atcha/common/redis/ProdRedisConfig.kt
> [Release] v1.6.3

- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationManager.kt
> [#192] notification push data 추가

- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/kakao/response/KakaoRouteResponse.kt
> [#194] 카카오 택시비 조회 에러 시 0원 반환

- deployment/prod/deploy.sh
- src/main/kotlin/com/deepromeet/atcha/common/redis/DefaultRedisConfig.kt
- src/main/kotlin/com/deepromeet/atcha/common/redis/ProdRedisConfig.kt
- close #188 
- 운영 환경 ip를 변경한다.
> [#188] 운영 환경 IP 변경

- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperations.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteReader.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicGyeonggiRouteInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/PublicSubwayInfoClient.kt
> [#204] 코루틴 디스패처 IO 풀 지정

- src/main/kotlin/com/deepromeet/atcha/location/api/controller/LocationController.kt
> [#208] 하드코딩 userId 제거

- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicBusResponse.kt
- close #210 
- 운행 종료된 버스의 첫차 및 막차 정보 조회 시 에러가 발생하여 조치하였습니다.
> [#210] 공공 데이터 API 응답 파싱 에러 처리

- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicBusResponse.kt
- close #213 
- 파싱 에러를 다시 처리합니다.
> [#213] 운행종료 버스 출발 및 막차시간 파싱 오류 수정

- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperations.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/SubwayTimeTable.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/response/PublicBusResponse.kt
> [Release] v1.7.2

- src/main/kotlin/com/deepromeet/atcha/notification/api/NotificationTestController.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/Messaging.kt
- close #223 
- Messaging 객체 생성 시 버그 수정
> [#223] FCM 형식 버그 수정

- src/main/kotlin/com/deepromeet/atcha/notification/api/NotificationTestController.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationContent.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationContentManager.kt
- src/main/kotlin/com/deepromeet/atcha/notification/domatin/NotificationType.kt
> [#225] NotificationType 추가

- src/main/kotlin/com/deepromeet/atcha/user/api/request/UserInfoUpdateRequest.kt
- src/main/kotlin/com/deepromeet/atcha/user/api/response/UserInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/user/api/response/UserInfoUpdateResponse.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserAppender.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserUpdateInfo.kt
- src/test/kotlin/com/deepromeet/atcha/user/UserControllerTest.kt
- close #232 
- 알림 빈도 수정을 추가합니다.
> [#232] 알림 빈도 수정 버그

- Dockerfile
> [#241] KST로 시간 변경

- src/main/kotlin/com/deepromeet/atcha/common/redis/LockRedisManager.kt
- src/main/kotlin/com/deepromeet/atcha/common/redis/ProdRedisConfig.kt
- close #244 
- 빈 충돌이 일어나는 빈의 이름을 분리해주었습니다.
> [#244] RedisTemplate 빈 충돌 문제 해결

- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperations.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitRouteClient.kt
> [#248] 출발시간 NPE 해결

- deployment/prod/deploy.sh
- src/main/kotlin/com/deepromeet/atcha/notification/infrastructure/redis/RedisStreamConsumer.kt
> [#251] 유저 알림 시간 체크 누락

- src/main/kotlin/com/deepromeet/atcha/notification/infrastructure/redis/RedisStreamConsumer.kt
> fix: RedisConsumer 롤백

- .github/workflows/auto-assignee-reviewer.yml
- src/main/kotlin/com/deepromeet/atcha/auth/api/request/SignUpRequest.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/Provider.kt
- src/main/kotlin/com/deepromeet/atcha/auth/domain/SignUpInfo.kt
- src/main/kotlin/com/deepromeet/atcha/auth/exception/AuthError.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/ProviderType.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/AppleFeignClient.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/AppleFeignConfig.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/AppleProvider.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/ApplePublicKey.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/ApplePublicKeys.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/AppleTokenParser.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/provider/apple/PublicKeyGenerator.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/response/KakaoUserInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/auth/infrastructure/response/ProviderUserInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/user/api/response/UserInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/user/api/response/UserInfoUpdateResponse.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/User.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserAppender.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserReader.kt
- src/main/kotlin/com/deepromeet/atcha/user/infrastructure/repository/UserJpaRepository.kt
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/kotlin/com/deepromeet/atcha/auth/AuthServiceTest.kt
- src/test/kotlin/com/deepromeet/atcha/support/fixture/UserFixture.kt
> [feat] 기존 인증 API 애플 로그인 적용

- deployment/dev/data/nginx/nginx-blue.conf
- deployment/dev/data/nginx/nginx-green.conf
- deployment/dev/data/nginx/nginx.conf
> [#246] nginx https 적용

- src/main/kotlin/com/deepromeet/atcha/common/logging/interceptor/DefaultLoggingInterceptor.kt
- src/main/kotlin/com/deepromeet/atcha/user/domain/UserAppender.kt
> [#270] 요청 로깅 파라미터 추가

- src/main/kotlin/com/deepromeet/atcha/transit/api/TransitController.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperationsV2.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitRouteClientV2.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
> [#283] 실시간 QA 버전 API 추가

- src/main/kotlin/com/deepromeet/atcha/common/feign/FeignConfig.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusRoutePositions.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusRouteResolver.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusRouteStation.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/BusTravelTimeCalculator.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/LastRouteOperations.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/cache/config/ApiCacheConfig.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/gyeonggi/PublicGyeonggiRouteInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/gyeonggi/response/GyeonggiBusRouteInfoResponse.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/incheon/PublicIncheonRouteInfoClient.kt
- src/main/kotlin/com/deepromeet/atcha/transit/infrastructure/client/public/seoul/PublicSeoulBusRouteInfoClient.kt
- src/main/resources/application.yml
> [#258] 버스 노선 및 경유 정류장 리스트 API 응답 캐시 적용

- src/main/kotlin/com/deepromeet/atcha/transit/domain/RouteDepartureTimeRefresher.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitService.kt
> [#294] 출발 시간 갱신이 지난 시간으로 되는 문제 해결

- src/main/kotlin/com/deepromeet/atcha/route/api/response/LastRouteResponse.kt
- src/main/kotlin/com/deepromeet/atcha/route/application/LastRouteCalculatorV2.kt
- src/main/kotlin/com/deepromeet/atcha/route/application/LastRouteLegCalculator.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/TransitInfo.kt
- src/main/kotlin/com/deepromeet/atcha/transit/domain/subway/SubwayTimeTable.kt
> [#333] 지하철 ~~행 정보 추가

- src/main/kotlin/com/deepromeet/atcha/route/api/RouteController.kt
- src/main/kotlin/com/deepromeet/atcha/route/application/LastRouteCalculator.kt
- src/main/kotlin/com/deepromeet/atcha/route/application/RouteService.kt
- src/main/kotlin/com/deepromeet/atcha/route/domain/RouteExtensions.kt
- src/main/kotlin/com/deepromeet/atcha/route/exception/RouteError.kt
> [#337] 막차 경로 0개인 경우 예외 처리
